### ISSUE TITLE
Gzip'ing broken?

### ISSUE THREAD

**Issue by andig** [aprice/embed#1]
After upgrading packages and migrating to go 1.11 I've started to notice that my embedded js app is no longer working. A quick test shows that gzipping might be the culprit:

    curl -s localhost:8080/static/js/app.js
    var meter...

while:

    curl -sH "Accept-Encoding: gzip" localhost:8080/static/js/app.js | gunzip -
    *rubbish*

This is with `embed.json` containing:

    "CompressPattern": "\\.(js|css|html)$",

When I invalidate compression with the `CompressPattern`, problem goes away, too.

Is it possible that gzip compression is broken in this library or go?

**Update** did a bisect and it appears that the problem was introduced in f6dc573. The commit before it is working, with this one its broken.

**Comment by andig** [comment]
**Update** did a bisect and it appears that the problem was introduced in f6dc57309fa0be67fd2a0eb4f79560fca1bb5cff. The commit before it is working, with this one its broken.

**Comment by aprice** [comment]
Using master@HEAD I'm not able to reproduce the issue - make sure you're using the latest version of the `embed` binary and the latest version of the `embed/loader` library within your project.

**Comment by andig** [comment]
Thanks for the quick reply. My testing steps are as follows (go 1.11):

  - Update `go.mod` with the respective aprice/embed commit hash
  - Generate the assets `go generate` which triggers fetching the library commit
  - Run application `go run cmd/server/main.go` and test using curl

This is the embedding comment:

    //go:generate go run github.com/aprice/embed/cmd/embed -c "embed.json"

That sequence should update both embed and loader?

**Comment by aprice** [comment]
That only updates the loader library. To update the embed binary you'd need to run `go get -u github.com/aprice/embed/cmd/embed`. Your `go run` command will build & run whatever you have locally, it won't update it.

**Comment by andig** [comment]
Still no help:

    ❯ go get -u github.com/aprice/embed/cmd/embed
    go: finding github.com/aprice/embed/cmd/embed latest
    go: finding github.com/aprice/embed/cmd latest
    go: finding github.com/aprice/embed latest

    ❯ go get -u github.com/aprice/embed

Then either

    ❯ go generate
    Embedded  /css/app.css
    Embedded  /css/bootstrap.min.css
    Embedded  /index.tmpl
    Embedded  /js/app.js
    Embedded  /js/bootstrap.min.js
    Embedded  /js/jquery-3.2.1.min.js
    Embedded  /js/tether.min.js
    Embedded  /js/vue.min.js
    Embedded  /simple.tmpl
    Generation complete in 195.487122ms

or

    ❯ go run github.com/aprice/embed/cmd/embed -c "embed.json"
    Embedded  /css/app.css
    Embedded  /css/bootstrap.min.css
    Embedded  /index.tmpl
    Embedded  /js/app.js
    Embedded  /js/bootstrap.min.js
    Embedded  /js/jquery-3.2.1.min.js
    Embedded  /js/tether.min.js
    Embedded  /js/vue.min.js
    Embedded  /simple.tmpl
    Generation complete in 194.430245ms

All give the same result. When I go back to the commit above problem goes away.

**Comment by andig** [comment]
Problem still exists. Updating the cmd *and* the package does not help:

    ~/htdocs/gosdm fix-tests* 12s
    ❯ rm $GOPATH/bin/embed

    ~/htdocs/gosdm fix-tests*
    ❯ go get -u github.com/aprice/embed/cmd/embed
    go: finding github.com/aprice/embed/cmd/embed latest
    go: finding github.com/aprice/embed/cmd latest
    go: finding github.com/aprice/embed latest

    ~/htdocs/gosdm fix-tests*
    ❯ ls $GOPATH/bin
    embed

    ~/htdocs/gosdm fix-tests*
    ❯ go generate
    Embedded  /css/app.css
    Embedded  /css/bootstrap.min.css
    Embedded  /index.html
    Embedded  /js/app.js
    Embedded  /js/bootstrap.min.js
    Embedded  /js/d3-format.min.js
    Embedded  /js/jquery-3.2.1.min.js
    Embedded  /js/tether.min.js
    Embedded  /js/vue.min.js
    Generation complete in 514.119666ms

`go.mod` shows that its the latest commit, too:

	github.com/aprice/embed v0.0.0-20171223211210-8e25a549692e

When I update `go.mod` to an earlier commit the problem is gone.

**Comment by andig** [comment]
@aprice I'm still (or again) seeing this when updating to a current version. For me it is breaking when updating my go.mod like this:

    -	github.com/aprice/embed v0.0.0-20171223211210-e0f543275bf966271e2c3b3ab70265f635f0394a
    +	github.com/aprice/embed v0.0.0-20181126214606-b9ceb1f6d22d

Verified checking curl output for the asset: 

    curl -sH 'Accept-encoding: gzip' localhost:8080/js/app.js | gunzip - 

Problem only exists with gzip, not with plain request. Happens for CSS and JS but funny enough not for the root html:

	// static
	router.HandleFunc("/", MkIndexHandler(mc))
	router.PathPrefix("/js/").Handler(GetEmbeddedContent())
	router.PathPrefix("/css/").Handler(GetEmbeddedContent())

This is the config:

	{
		"RootPath": "assets",
		"Recurse": true,
		"IncludePattern": "",
		"ExcludePattern": "(^\\.|\\.go$)",
		"OutputPath": "embeddedassets.go",
		"BuildConstraints": "",
		"PackageName": "sdm630",
		"DevOutputPath": "",
		"DevBuildConstraints": "",
		"MinifyTypes": {
			"\\.html?$": "text/html",
			"\\.css$": "text/css",
			"\\.js$": "application/javascript"
		},
		"CompressPattern": "\\.(js|css|html)$",
		"NoCompressPattern": "\\.(pe?g|png|gif|woff2?|eot|ttf|ico)$",
		"OverrideModDate": false
	}

If you want to reproduce you can use https://github.com/gonium/gosdm630 and run like this:

    make assets && go run -race cmd/sdm/main.go -s -u localhost:8080 -r 1 

I would appreciate any help as its driving me nuts...

**Comment by andig** [comment]
I've finally given up and switched to http://github.com/mjibson/esc which provides similar functionality for my purposes.
